import React, { useState, useRef, useEffect } from 'react';
import { Send, Mic, MicOff, Volume2, VolumeX, Bot, User, Sparkles, MessageSquare, Zap, History, Trash2, AlertCircle, CheckCircle, RefreshCw } from 'lucide-react';
import { useAuth } from '../contexts/AuthContext';
import { chatService } from '../services/api';

interface Message {
  id?: string; // Optional, as it might be generated by backend
  text: string;
  sender: 'user' | 'bot';
  timestamp: Date;
}

const Chatbot: React.FC = () => {
  const { user } = useAuth();
  const [messages, setMessages] = useState<Message[]>([
    {
      id: '1',
      text: 'Hello! I\'m your AI agriculture assistant powered by advanced AI models. I can help you with farming questions, crop advice, weather information, and government schemes. How can I assist you today? 🌱',
      sender: 'bot',
      timestamp: new Date()
    }
  ]);
  const [inputText, setInputText] = useState('');
  const [isListening, setIsListening] = useState(false);
  const [isSpeaking, setIsSpeaking] = useState(false);
  const [isTyping, setIsTyping] = useState(false);
  const [isAiAvailable, setIsAiAvailable] = useState(false);
  const [currentSessionId, setCurrentSessionId] = useState<string>(''); // Will be set from history or new session
  const [error, setError] = useState<string | null>(null);
  const [connectionStatus, setConnectionStatus] = useState<'checking' | 'connected' | 'fallback'>('checking');
  const [chatSessions, setChatSessions] = useState<string[]>([]); // To store list of session IDs
  const [showHistoryModal, setShowHistoryModal] = useState(false);
  const messagesEndRef = useRef<HTMLDivElement>(null);
  const recognitionRef = useRef<SpeechRecognition | null>(null);

  const scrollToBottom = () => {
    messagesEndRef.current?.scrollIntoView({ behavior: 'smooth' });
  };

  useEffect(() => {
    scrollToBottom();
  }, [messages]);

 // Initialize current session or load history
  useEffect(() => {
    if (user) {
      // Try to load a default session or create a new one
      const defaultSessionId = `session_${user.id}`; // A consistent session ID for the user
      setCurrentSessionId(defaultSessionId);
      loadChatHistory(defaultSessionId);
      fetchChatSessions(); // Fetch all sessions for the user
    }
  }, [user]);

  const checkAiService = async () => {
    // For now, we assume AI is available if backend is running
    // In a real scenario, you might have a backend endpoint to check OpenRouter status
    setConnectionStatus('connected');
    setIsAiAvailable(true);
    setError(null);
  };

  const loadChatHistory = async (sessionIdToLoad: string) => {
    if (!user) return;
    try {
      const response = await chatService.getChatHistory(sessionIdToLoad);
      const loadedMessages = response.messages.map(msg => ({
        id: msg.id,
        text: msg.text,
        sender: msg.sender,
        timestamp: new Date(msg.timestamp)
      }));
      setMessages([
        {
          id: '1',
          text: 'Hello! I\'m your AI agriculture assistant powered by advanced AI models. I can help you with farming questions, crop advice, weather information, and government schemes. How can I assist you today? 🌱',
          sender: 'bot',
          timestamp: new Date()
        },
        ...loadedMessages
      ]);
      setCurrentSessionId(sessionIdToLoad);
    } catch (error) {
      console.error('Error loading chat history:', error);
      setError('Failed to load chat history. Starting a new session.');
      setMessages([
        {
          id: '1',
          text: 'Hello! I\'m your AI agriculture assistant powered by advanced AI models. I can help you with farming questions, crop advice, weather information, and government schemes. How can I assist you today? 🌱',
          sender: 'bot',
          timestamp: new Date()
        }
      ]);
    }
  };

  const fetchChatSessions = async () => {
    if (!user) return;
    try {
      // Assuming a new backend endpoint to get all session IDs for a user
      // For now, let's mock it or assume we get it from history endpoint
      // This needs a new backend route if not already present
      // For now, we'll just use the default session ID
      setChatSessions([`session_${user.id}`]); // Placeholder
    } catch (error) {
      console.error('Error fetching chat sessions:', error);
    }
  };

  // Initialize speech recognition
  useEffect(() => {
    if ('webkitSpeechRecognition' in window || 'SpeechRecognition' in window) {
      const SpeechRecognition = window.SpeechRecognition || window.webkitSpeechRecognition;
      recognitionRef.current = new SpeechRecognition();
      recognitionRef.current.continuous = false;
      recognitionRef.current.interimResults = false;
      recognitionRef.current.lang = 'en-US';

      recognitionRef.current.onresult = (event) => {
        const transcript = event.results[0][0].transcript;
        setInputText(transcript);
        setIsListening(false);
      };

      recognitionRef.current.onerror = (event) => {
        console.error('Speech recognition error:', event.error);
        setIsListening(false);
        setError('Speech recognition failed. Please try again or type your message.');
      };

      recognitionRef.current.onend = () => {
        setIsListening(false);
      };
    }
  }, []);

  const startListening = () => {
    if (recognitionRef.current && !isListening) {
      setError(null);
      setIsListening(true);
      try {
        recognitionRef.current.start();
      } catch (error) {
        console.error('Error starting speech recognition:', error);
        setIsListening(false);
        setError('Could not start speech recognition. Please check your microphone permissions.');
      }
    }
  };

  const stopListening = () => {
    if (recognitionRef.current && isListening) {
      recognitionRef.current.stop();
      setIsListening(false);
    }
  };

  const speak = (text: string) => {
    if ('speechSynthesis' in window) {
      // Stop any ongoing speech
      speechSynthesis.cancel();
      
      const utterance = new SpeechSynthesisUtterance(text);
      utterance.onstart = () => setIsSpeaking(true);
      utterance.onend = () => setIsSpeaking(false);
      utterance.onerror = () => setIsSpeaking(false);
      
      speechSynthesis.speak(utterance);
    }
  };

  const stopSpeaking = () => {
    if ('speechSynthesis' in window) {
      speechSynthesis.cancel();
      setIsSpeaking(false);
    }
  };

  const handleSendMessage = async () => {
    if (!inputText.trim()) return;

    setError(null);
    const userMessage: Message = {
      id: Date.now().toString(),
      text: inputText.trim(),
      sender: 'user',
      timestamp: new Date()
    };
 setMessages(prev => [...prev, userMessage]);

    // Save user message to backend
    if (user) {
      try {
        await chatService.saveMessage(userMessage.text, 'user', currentSessionId);
      } catch (error) {
        console.error('Error saving user message to backend:', error);
        setError('Failed to save user message. Please check your connection.');
      }
    }

    const userInput = inputText.trim();
    setInputText('');
    setIsTyping(true);

    try {
      // Call backend for chatbot response
      const response = await chatService.sendMessage(userInput, currentSessionId);
      const botResponse = response.reply;

      const botMessage: Message = {
        id: (Date.now() + 1).toString(), // Temporary ID, backend will assign real one
        text: botResponse,
        sender: 'bot',
        timestamp: new Date()
      };

      setMessages(prev => [...prev, botMessage]);

      // Save bot response to backend
      if (user) {
        try {
          await chatService.saveMessage(botResponse, 'bot', currentSessionId);
        } catch (error) {
          console.error('Error saving bot message to backend:', error);
          setError('Failed to save bot message. Please check your connection.');
        }
      }
    } catch (error) {
      console.error('Error generating response from backend:', error);
      const errorMessage: Message = {
        id: (Date.now() + 1).toString(),
        text: 'I apologize, but I encountered an error while processing your request. Please try asking your question again, or try asking about specific farming topics like crop cultivation, pest management, or government schemes.',
        sender: 'bot',
        timestamp: new Date()
      };
      setMessages(prev => [...prev, errorMessage]);
      setError('Failed to get response from AI. Please try again with a specific farming question.');
    } finally {
      setIsTyping(false);
    }
  };


  const handleKeyPress = (e: React.KeyboardEvent) => {
    if (e.key === 'Enter' && !e.shiftKey) {
      e.preventDefault();
      handleSendMessage();
    }
  };

   const clearChat = () => {
    // This will clear the current view, but not delete from backend
    setMessages([{
      id: '1',
      text: 'Hello! I\'m your AI agriculture assistant. How can I help you today? 🌱',
      sender: 'bot',
      timestamp: new Date()
    }]);
    setError(null);
    // Optionally, create a new session ID here if clearing means starting fresh
    setCurrentSessionId(`session_${user?.id}_${Date.now()}`);
  };

  const deleteCurrentChatSession = async () => {
    if (!user || !currentSessionId) return;
    if (window.confirm('Are you sure you want to delete this entire chat session? This action cannot be undone.')) {
      try {
        await chatService.deleteChatSession(currentSessionId);
        alert('Chat session deleted successfully!');
        // After deletion, clear current chat and start a new session
        setMessages([{
          id: '1',
          text: 'Hello! I\'m your AI agriculture assistant. How can I help you today? 🌱',
          sender: 'bot',
          timestamp: new Date()
        }]);
        setCurrentSessionId(`session_${user.id}_${Date.now()}`); // Start a new session
        fetchChatSessions(); // Refresh the list of sessions
        setError(null);
      } catch (error) {
        console.error('Error deleting chat session:', error);
        setError('Failed to delete chat session.');
      }
    }
  };

  const handleLoadSession = (sessionId: string) => {
    setShowHistoryModal(false);
    loadChatHistory(sessionId);
  };

  const handleDeleteSession = async (sessionId: string) => {
    if (!user) return;
    if (window.confirm(`Are you sure you want to delete session "${sessionId}"?`)) {
      try {
        await chatService.deleteChatSession(sessionId);
        alert('Session deleted successfully!');
        fetchChatSessions(); // Refresh the list of sessions
        if (currentSessionId === sessionId) {
          // If current session was deleted, start a new one
          setMessages([{
            id: '1',
            text: 'Hello! I\'m your AI agriculture assistant. How can I help you today? 🌱',
            sender: 'bot',
            timestamp: new Date()
          }]);
          setCurrentSessionId(`session_${user.id}_${Date.now()}`);
        }
      } catch (error) {
        console.error('Error deleting session:', error);
        setError('Failed to delete session.');
      }
    }
  };

  const quickQuestions = [
    'How to grow rice effectively?',
    'What fertilizers for wheat?',
    'Weather forecast impact on crops',
    'Government schemes for farmers',
    'Pest control for cotton',
    'Soil testing importance',
    'Organic farming benefits',
    'Irrigation best practices'
  ];

  const getConnectionStatusColor = () => {
    switch (connectionStatus) {
      case 'connected': return 'bg-green-500/20 text-green-200';
      case 'fallback': return 'bg-yellow-500/20 text-yellow-200';
      case 'checking': return 'bg-blue-500/20 text-blue-200';
      default: return 'bg-gray-500/20 text-gray-200';
    }
  };

  const getConnectionStatusText = () => {
    switch (connectionStatus) {
      case 'connected': return 'AI Connected';
      case 'fallback': return 'Enhanced Knowledge Base';
      case 'checking': return 'Connecting...';
      default: return 'Offline Mode';
    }
  };

  return (
    <div className="space-y-8">
      {/* Header Section */}
      <div className="relative overflow-hidden bg-gradient-to-r from-purple-600 via-indigo-600 to-blue-600 dark:from-purple-700 dark:via-indigo-700 dark:to-blue-700 rounded-3xl p-8 text-white shadow-2xl">
        <div className="absolute inset-0 bg-black/10"></div>
        <div className="absolute top-0 right-0 w-64 h-64 bg-white/10 rounded-full -translate-y-32 translate-x-32"></div>
        <div className="absolute bottom-0 left-0 w-48 h-48 bg-white/5 rounded-full translate-y-24 -translate-x-24"></div>
        
        <div className="relative z-10">
          <div className="flex items-center justify-between">
            <div>
              <h1 className="text-4xl font-bold mb-3 flex items-center">
                AI Agriculture Assistant 
                <Sparkles className="h-8 w-8 ml-3 text-yellow-300" />
              </h1>
              <p className="text-purple-100 text-lg max-w-3xl">
                Get intelligent answers with voice input and audio responses. Enhanced with comprehensive agriculture knowledge base for reliable farming guidance.
              </p>
              <div className="flex items-center space-x-4 mt-4">
                <div className={`flex items-center space-x-2 px-3 py-1 rounded-full ${getConnectionStatusColor()}`}>
                  <div className={`w-2 h-2 rounded-full ${connectionStatus === 'connected' ? 'bg-green-400' : connectionStatus === 'fallback' ? 'bg-yellow-400' : 'bg-blue-400'} animate-pulse`}></div>
                  <span className="text-sm">{getConnectionStatusText()}</span>
                </div>
                {user && (
                  <div className="flex items-center space-x-2 px-3 py-1 bg-blue-500/20 text-blue-200 rounded-full">
                    <History className="h-4 w-4" />
                    <span className="text-sm">History Saved</span>
                  </div>
                )}
              </div>
            </div>
            <div className="hidden lg:block">
              <div className="w-32 h-32 bg-white/20 backdrop-blur-sm rounded-full flex items-center justify-center">
                <Bot className="h-16 w-16 text-white" />
              </div>
            </div>
          </div>
        </div>
      </div>

      {/* Error Display */}
      {error && (
        <div className="bg-yellow-50 dark:bg-yellow-900/20 border border-yellow-200 dark:border-yellow-800 rounded-2xl p-6">
          <div className="flex items-center space-x-3">
            <AlertCircle className="h-6 w-6 text-yellow-500" />
            <p className="text-yellow-700 dark:text-yellow-400 font-medium">{error}</p>
          </div>
        </div>
      )}

      {/* Voice Controls */}
      <div className="bg-white dark:bg-gray-800 rounded-3xl p-8 shadow-xl border border-gray-100 dark:border-gray-700">
        <div className="flex items-center space-x-3 mb-6">
          <Zap className="h-6 w-6 text-purple-600 dark:text-purple-400" />
          <h2 className="text-2xl font-bold text-gray-800 dark:text-white">Voice Controls & Chat Management</h2>
        </div>
        
        <div className="flex flex-wrap items-center gap-4">
          <button
            onClick={isListening ? stopListening : startListening}
            disabled={!('webkitSpeechRecognition' in window || 'SpeechRecognition' in window)}
            className={`flex items-center space-x-3 px-6 py-3 rounded-xl font-medium transition-all duration-200 transform hover:scale-105 disabled:opacity-50 disabled:cursor-not-allowed ${
              isListening 
                ? 'bg-red-500 hover:bg-red-600 text-white shadow-lg' 
                : 'bg-blue-500 hover:bg-blue-600 text-white shadow-lg'
            }`}
          >
            {isListening ? <MicOff className="h-5 w-5" /> : <Mic className="h-5 w-5" />}
            <span>{isListening ? 'Stop Listening' : 'Voice Input'}</span>
            {isListening && <div className="w-2 h-2 bg-white rounded-full animate-pulse"></div>}
          </button>

          <button
            onClick={isSpeaking ? stopSpeaking : () => {}}
            disabled={!isSpeaking}
            className={`flex items-center space-x-3 px-6 py-3 rounded-xl font-medium transition-all duration-200 ${
              isSpeaking 
                ? 'bg-orange-500 hover:bg-orange-600 text-white shadow-lg' 
                : 'bg-gray-300 dark:bg-gray-600 text-gray-500 dark:text-gray-400 cursor-not-allowed'
            }`}
          >
            {isSpeaking ? <VolumeX className="h-5 w-5" /> : <Volume2 className="h-5 w-5" />}
            <span>{isSpeaking ? 'Stop Speaking' : 'Voice Output'}</span>
            {isSpeaking && <div className="w-2 h-2 bg-white rounded-full animate-bounce"></div>}
          </button>

     <button
          onClick={clearChat}
          className="flex items-center space-x-3 px-6 py-3 rounded-xl font-medium transition-all duration-200 bg-gray-500 hover:bg-gray-600 text-white shadow-lg"
        >
          <RefreshCw className="h-5 w-5" />
          <span>New Chat</span>
        </button>

        <button
          onClick={() => setShowHistoryModal(true)}
          className="flex items-center space-x-3 px-6 py-3 rounded-xl font-medium transition-all duration-200 bg-indigo-500 hover:bg-indigo-600 text-white shadow-lg"
        >
          <History className="h-5 w-5" />
          <span>View History</span>
        </button>

        <button
          onClick={deleteCurrentChatSession}
          disabled={messages.length <= 1} // Disable if only initial message
          className="flex items-center space-x-3 px-6 py-3 rounded-xl font-medium transition-all duration-200 bg-red-500 hover:bg-red-600 text-white shadow-lg disabled:opacity-50 disabled:cursor-not-allowed"
        >
          <Trash2 className="h-5 w-5" />
          <span>Delete Current Chat</span>
        </button>

          <button
            onClick={checkAiService}
            className="flex items-center space-x-3 px-6 py-3 rounded-xl font-medium transition-all duration-200 bg-purple-500 hover:bg-purple-600 text-white shadow-lg"
          >
            <RefreshCw className={`h-5 w-5 ${connectionStatus === 'checking' ? 'animate-spin' : ''}`} />
            <span>Test Connection</span>
          </button>

          <div className="flex items-center space-x-2 text-sm text-gray-600 dark:text-gray-400 bg-gray-100 dark:bg-gray-700 px-4 py-2 rounded-lg">
            <MessageSquare className="h-4 w-4" />
            <span>{messages.length - 1} messages exchanged</span>
          </div>
        </div>
      </div>

      {/* Chat Container */}
      <div className="bg-white dark:bg-gray-800 rounded-3xl shadow-2xl flex flex-col h-[600px] border border-gray-100 dark:border-gray-700">
        {/* Chat Header */}
        <div className="p-6 border-b border-gray-200 dark:border-gray-700 bg-gradient-to-r from-purple-50 to-indigo-50 dark:from-purple-900/20 dark:to-indigo-900/20 rounded-t-3xl">
          <div className="flex items-center space-x-3">
            <div className="w-12 h-12 bg-gradient-to-r from-purple-500 to-indigo-600 rounded-full flex items-center justify-center">
              <Bot className="h-6 w-6 text-white" />
            </div>
            <div>
              <h3 className="font-bold text-gray-800 dark:text-white">AI Agriculture Assistant</h3>
              <div className="flex items-center space-x-2">
                <div className={`w-2 h-2 rounded-full animate-pulse ${connectionStatus === 'connected' ? 'bg-green-500' : connectionStatus === 'fallback' ? 'bg-yellow-500' : 'bg-blue-500'}`}></div>
                <span className="text-sm text-gray-600 dark:text-gray-400">
                  {connectionStatus === 'connected' ? 'AI-Powered Responses' : 'Enhanced Knowledge Base'}
                </span>
              </div>
            </div>
          </div>
        </div>

        {/* Messages */}
        <div className="flex-1 overflow-y-auto p-6 space-y-6">
          {messages.map((message) => (
            <div
              key={message.id}
              className={`flex ${message.sender === 'user' ? 'justify-end' : 'justify-start'}`}
            >
              <div className={`flex items-start space-x-3 max-w-xs lg:max-w-md ${message.sender === 'user' ? 'flex-row-reverse space-x-reverse' : ''}`}>
                <div className={`flex-shrink-0 w-10 h-10 rounded-full flex items-center justify-center ${
                  message.sender === 'bot' 
                    ? 'bg-gradient-to-r from-purple-500 to-indigo-600' 
                    : 'bg-gradient-to-r from-blue-500 to-cyan-600'
                }`}>
                  {message.sender === 'bot' ? (
                    <Bot className="h-5 w-5 text-white" />
                  ) : (
                    <User className="h-5 w-5 text-white" />
                  )}
                </div>
                
                <div
                  className={`px-6 py-4 rounded-2xl shadow-lg ${
                    message.sender === 'user'
                      ? 'bg-gradient-to-r from-blue-500 to-cyan-600 text-white'
                      : 'bg-gray-100 dark:bg-gray-700 text-gray-800 dark:text-white border border-gray-200 dark:border-gray-600'
                  }`}
                >
                  <p className="text-sm leading-relaxed">{message.text}</p>
                  {message.sender === 'bot' && (
                    <button
                      onClick={() => speak(message.text)}
                      disabled={isSpeaking}
                      className="mt-3 flex items-center space-x-2 text-xs text-gray-500 dark:text-gray-400 hover:text-gray-700 dark:hover:text-gray-300 transition-colors disabled:opacity-50"
                    >
                      <Volume2 className="h-3 w-3" />
                      <span>Listen to response</span>
                    </button>
                  )}
                  <div className="mt-2 text-xs opacity-70">
                    {message.timestamp.toLocaleTimeString([], { hour: '2-digit', minute: '2-digit' })}
                  </div>
                </div>
              </div>
            </div>
          ))}

          {isTyping && (
            <div className="flex justify-start">
              <div className="flex items-start space-x-3">
                <div className="flex-shrink-0 w-10 h-10 bg-gradient-to-r from-purple-500 to-indigo-600 rounded-full flex items-center justify-center">
                  <Bot className="h-5 w-5 text-white" />
                </div>
                <div className="bg-gray-100 dark:bg-gray-700 px-6 py-4 rounded-2xl border border-gray-200 dark:border-gray-600">
                  <div className="flex space-x-2">
                    <div className="w-2 h-2 bg-gray-400 rounded-full animate-bounce"></div>
                    <div className="w-2 h-2 bg-gray-400 rounded-full animate-bounce" style={{ animationDelay: '0.1s' }}></div>
                    <div className="w-2 h-2 bg-gray-400 rounded-full animate-bounce" style={{ animationDelay: '0.2s' }}></div>
                  </div>
                </div>
              </div>
            </div>
          )}
          
          <div ref={messagesEndRef} />
        </div>

        {/* Input Area */}
        <div className="border-t border-gray-200 dark:border-gray-700 p-6 bg-gray-50 dark:bg-gray-800/50 rounded-b-3xl">
          <div className="flex items-center space-x-4">
            <div className="flex-1 relative">
              <textarea
                value={inputText}
                onChange={(e) => setInputText(e.target.value)}
                onKeyPress={handleKeyPress}
                placeholder="Ask me about farming, crops, weather, or government schemes..."
                className="w-full resize-none border-2 border-gray-300 dark:border-gray-600 bg-white dark:bg-gray-700 text-gray-800 dark:text-white rounded-2xl px-6 py-4 focus:outline-none focus:ring-2 focus:ring-purple-500 focus:border-transparent transition-all duration-200 placeholder-gray-500 dark:placeholder-gray-400"
                rows={1}
                disabled={isTyping}
              />
            </div>
            <button
              onClick={handleSendMessage}
              disabled={!inputText.trim() || isTyping}
              className="bg-gradient-to-r from-purple-500 to-indigo-600 hover:from-purple-600 hover:to-indigo-700 disabled:from-gray-300 disabled:to-gray-400 disabled:cursor-not-allowed text-white p-4 rounded-2xl transition-all duration-200 transform hover:scale-105 shadow-lg"
            >
              <Send className="h-5 w-5" />
            </button>
          </div>
        </div>
      </div>

      {/* Quick Questions */}
      <div className="bg-white dark:bg-gray-800 rounded-3xl p-8 shadow-xl border border-gray-100 dark:border-gray-700">
        <div className="flex items-center space-x-3 mb-6">
          <Sparkles className="h-6 w-6 text-purple-600 dark:text-purple-400" />
          <h3 className="text-2xl font-bold text-gray-800 dark:text-white">Quick Questions</h3>
        </div>
        
        <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-4 gap-4">
          {quickQuestions.map((question, index) => (
            <button
              key={index}
              onClick={() => setInputText(question)}
              disabled={isTyping}
              className="group text-left p-4 bg-gradient-to-br from-purple-50 to-indigo-50 dark:from-purple-900/20 dark:to-indigo-900/20 hover:from-purple-100 hover:to-indigo-100 dark:hover:from-purple-900/30 dark:hover:to-indigo-900/30 rounded-xl transition-all duration-200 text-sm text-gray-700 dark:text-gray-300 border border-purple-200 dark:border-purple-800 hover:border-purple-300 dark:hover:border-purple-600 transform hover:-translate-y-1 hover:shadow-lg disabled:opacity-50 disabled:cursor-not-allowed"
            >
              <div className="flex items-center space-x-2">
                <MessageSquare className="h-4 w-4 text-purple-500 group-hover:text-purple-600" />
                <span className="font-medium">{question}</span>
              </div>
            </button>
          ))}
        </div>
      </div>

      {/* Status Information */}
      <div className="bg-gradient-to-r from-green-50 to-blue-50 dark:from-green-900/20 dark:to-blue-900/20 rounded-3xl p-8 shadow-xl border border-green-200 dark:border-green-800">
        <div className="grid grid-cols-1 md:grid-cols-3 gap-6">
          <div className="text-center">
            <div className="inline-flex p-4 bg-green-500 dark:bg-green-600 rounded-full mb-4">
              <CheckCircle className="h-8 w-8 text-white" />
            </div>
            <h3 className="text-lg font-bold text-gray-800 dark:text-white mb-2">Enhanced Knowledge</h3>
            <p className="text-gray-600 dark:text-gray-400 text-sm">Comprehensive agriculture database with expert guidance</p>
          </div>
          
          <div className="text-center">
            <div className="inline-flex p-4 bg-blue-500 dark:bg-blue-600 rounded-full mb-4">
              <Sparkles className="h-8 w-8 text-white" />
            </div>
            <h3 className="text-lg font-bold text-gray-800 dark:text-white mb-2">AI-Powered</h3>
            <p className="text-gray-600 dark:text-gray-400 text-sm">Advanced AI models for intelligent responses</p>
          </div>
          
          <div className="text-center">
            <div className="inline-flex p-4 bg-purple-500 dark:bg-purple-600 rounded-full mb-4">
              <Volume2 className="h-8 w-8 text-white" />
            </div>
            <h3 className="text-lg font-bold text-gray-800 dark:text-white mb-2">Voice Enabled</h3>
            <p className="text-gray-600 dark:text-gray-400 text-sm">Speak your questions and hear responses</p>
          </div>
    </div>
  </div>

  {/* Chat History Modal */}
  {showHistoryModal && (
    <div className="fixed inset-0 bg-black bg-opacity-50 flex items-center justify-center z-50 p-4">
      <div className="bg-white dark:bg-gray-800 rounded-3xl shadow-2xl p-8 w-full max-w-md max-h-[80vh] overflow-y-auto">
        <div className="flex justify-between items-center mb-6">
          <h2 className="text-2xl font-bold text-gray-800 dark:text-white">Chat History</h2>
          <button
            onClick={() => setShowHistoryModal(false)}
            className="text-gray-500 hover:text-gray-700 dark:text-gray-400 dark:hover:text-gray-200"
          >
            &times;
          </button>
        </div>
        {chatSessions.length === 0 ? (
          <p className="text-gray-600 dark:text-gray-400">No chat sessions found.</p>
        ) : (
          <ul className="space-y-4">
            {chatSessions.map((sessionId) => (
              <li key={sessionId} className="flex items-center justify-between bg-gray-50 dark:bg-gray-700 p-4 rounded-xl shadow-sm">
                <span
                  className="text-gray-800 dark:text-white cursor-pointer hover:text-purple-600 dark:hover:text-purple-400 font-medium"
                  onClick={() => handleLoadSession(sessionId)}
                >
                  {sessionId.replace('session_', 'Session ')}
                </span>
                <button
                  onClick={() => handleDeleteSession(sessionId)}
                  className="text-red-500 hover:text-red-700 dark:text-red-400 dark:hover:text-red-200 ml-4"
                >
                  <Trash2 className="h-5 w-5" />
                </button>
              </li>
            ))}
          </ul>
        )}
      </div>
    </div>
  )}
</div>


  );
};

export default Chatbot;